title: "TSM-Net"
tagline: "Temporal Compressing Autoencoder with Adversarial Losses for Time-Scale Modification on Audio Signals."
baseurl: "/melgan"
arxiv: "TODO"
repo:  "https://github.com/melgan-neurips/melgan-neurips.github.io"
author:
  name:
  url:
markdown: kramdown
